### ISSUE TITLE
Error message appears when submitting a comment

### ISSUE THREAD

**Issue by Tr33beard** [CallidusAsinus/munchkindb#6]
![image](https://user-images.githubusercontent.com/16105479/37744407-5d83e460-2d45-11e8-84df-75d752e1e96b.png)

This error message appears when a comment is submitted. Upon reloading, the comment does not appear.

**Comment by CallidusAsinus** [comment]
Where exactly were you trying to post a comment? Are you still unable to post the comment? Are you logged in when posting?

**Comment by Tr33beard** [comment]
I am logged in. 
I was attempting to post a comment on this decklist.
https://munchkindb.com/app.php/en/decklist/5/time-after-time
I was unable to post the comment or a comment on any other decklist.

**Comment by CallidusAsinus** [comment]
The issue was that the app was trying to send emails for every comment, but emailing hasn't been configured on the server yet. I've disabled the email-on-comment system for now.
