### ISSUE TITLE
Decklists on mobile showing several comments but only displaying 1

### ISSUE THREAD

**Issue by Tr33beard** [CallidusAsinus/munchkindb#7]
So on my weapon control warrior decklist, it says that there's 6 comments but, at the very least on mobile, I'm only seeing 1. Other decklists I'm not seeing this issue

**Comment by CallidusAsinus** [comment]
issue was in the db. I manually deleted some comments, but that number is not computed but rather stored elsewhere. Problem should be fixed when the app's cache refreshes (don't know how long this will be, could be hours or days).
